# Generated by Django 5.0.14 on 2026-02-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverificationotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiontier',
            name='daily_credits',
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='interval',
            field=models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly')], default='month', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
