# Generated by Django 5.0.14 on 2026-02-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_subscriptiontier_daily_credits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiontier',
            name='description',
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='features',
            field=models.JSONField(default=list),
        ),
    ]
