# Generated by Django 5.0.1 on 2026-02-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_subscriptiontier_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontier',
            name='credit_discount_percent',
            field=models.IntegerField(default=0),
        ),
    ]
