# Generated by Django 5.0.1 on 2026-02-27 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_subscriptiontier_credit_discount_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiontier',
            name='stripe_price_id',
        ),
    ]
