# Generated by Django 5.0.1 on 2026-02-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_subscriptiontier_stripe_price_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='credittransactionlog',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
