# Generated by Django 5.0.1 on 2026-03-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_creditbalance_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransactionlog',
            name='description',
            field=models.TextField(),
        ),
    ]
