# Generated by Django 5.0.14 on 2026-07-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_credittransactionlog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditbalance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=12),
        ),
    ]
