# Generated by Django 5.0.14 on 2026-07-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_creditbalance_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditbalance',
            name='last_daily_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
    ]
