# Generated by Django 5.0.14 on 2026-07-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_creditbalance_last_daily_reset_date_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creator_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
