# Generated by Django 5.0.14 on 2026-02-20 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, help_text='High-level summary of the lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='lesson',
            name='playground',
            field=models.JSONField(blank=True, help_text='Config for the interactive playground', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='quiz',
            field=models.JSONField(blank=True, help_text='Config for the assessment quiz', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='week_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='difficulty',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='total_estimated_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, help_text='Markdown content of the lesson'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['roadmap', 'week_number', 'day_number'], name='roadmaps_le_roadmap_77c888_idx'),
        ),
        migrations.AddIndex(
            model_name='roadmap',
            index=models.Index(fields=['user', 'created_at'], name='roadmaps_ro_user_id_3f6702_idx'),
        ),
    ]
