# Generated by Django 5.0.14 on 2026-02-23 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0004_rename_playground_lesson_playground_metadata_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='mode',
            field=models.CharField(choices=[('MATH', 'Mathematics'), ('LANGUAGE', 'Language'), ('CODE', 'Programming'), ('GENERAL', 'General')], default='GENERAL', max_length=10),
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IMAGE_TO_TEXT', 'Image to Text'), ('TEXT_TO_TRANSLATION', 'Text to Translation')], max_length=20)),
                ('front_content', models.TextField(help_text='URL for image or Text in target language')),
                ('back_content', models.TextField(help_text='Text in target language or Native translation')),
                ('phonetic', models.CharField(blank=True, max_length=255, null=True)),
                ('mastery_level', models.IntegerField(default=0, help_text='Spaced repetition tracking level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='roadmaps.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'mastery_level'], name='roadmaps_fl_user_id_00a86d_idx')],
                'unique_together': {('user', 'lesson', 'front_content')},
            },
        ),
    ]
