# Generated by Django 5.0.14 on 2026-02-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0005_alter_lesson_mode_flashcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='selected_mode',
            field=models.CharField(blank=True, help_text='User selected mode for the entire roadmap', max_length=15, null=True),
        ),
    ]
