# Generated by Django 5.0.14 on 2026-02-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0006_roadmap_selected_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='generated_lessons_count',
            field=models.PositiveIntegerField(default=0, help_text='Lessons created so far'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='total_lessons_count',
            field=models.PositiveIntegerField(default=0, help_text='Total lessons planned by AI'),
        ),
    ]
