# Generated by Django 5.0.1 on 2026-03-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0007_roadmap_generated_lessons_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='has_playground',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='playground_code',
            field=models.TextField(blank=True, help_text='Raw HTML/JS/CSS for the interactive simulation', null=True),
        ),
    ]
