# Generated by Django 5.0.1 on 2026-03-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0008_lesson_has_playground_lesson_playground_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='playground_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='not_started', max_length=20),
        ),
    ]
