# Generated by Django 5.0.1 on 2026-03-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0009_lesson_playground_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='last_error',
            field=models.TextField(blank=True, help_text='Last error message or traceback', null=True),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='last_error',
            field=models.TextField(blank=True, help_text='Last error message or traceback', null=True),
        ),
    ]
