# Generated by Django 5.0.1 on 2026-03-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0010_lesson_last_error_roadmap_last_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Soft delete flag to hide roadmap from user view'),
        ),
    ]
