# Generated by Django 5.0.1 on 2026-03-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0011_roadmap_is_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='week_title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='roadmap',
            name='topic',
            field=models.TextField(),
        ),
    ]
