# Generated by Django 5.0.14 on 2026-03-23 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0012_alter_lesson_title_alter_lesson_week_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonInteractionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat_attachments/%Y/%m/%d/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='roadmaps.lessoninteraction')),
            ],
        ),
    ]
