# Generated by Django 5.0.14 on 2026-07-14 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0013_lessoninteractionattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('FILE', 'File (PDF)'), ('URL', 'Website URL'), ('TEXT', 'Raw Text')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='roadmap_sources/%Y/%m/%d/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('text_content', models.TextField(blank=True, help_text='Raw text or clean parsed content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_sources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='roadmap',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='roadmaps', to='roadmaps.roadmapsource'),
        ),
    ]
