# Generated by Django 5.0.14 on 2026-07-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0015_lesson_is_preview_course_promocode_coursepurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, help_text='Direct discount percentage on the course'),
        ),
    ]
