# Generated by Django 5.0.14 on 2026-07-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0016_course_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='image_url',
            field=models.TextField(blank=True, help_text='Generated image Data URI or URL for visual learning', null=True),
        ),
    ]
