# Generated by Django 5.0.1 on 2026-02-27 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_creditbonusrule_creditpricing_exchangerate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditpack',
            name='stripe_price_id',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='stripe_session_id',
        ),
    ]
