# Generated by Django 5.0.1 on 2026-03-13 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_creditpack_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='octo_payment_UUID',
            new_name='provider_transaction_id',
        ),
    ]
